### PR TITLE
Перевод комментариев. Ссылки и заимствование

### PR DESCRIPTION
**Pull request by Gordon-F**
This change is [Reviewable](https://reviewable.io/reviews/rurust/rust_book_ru/60)

### CODE REVIEW

**Comment by mkpankov** [comment]
https://travis-ci.org/ruRust/rust_book_ru/builds/179984553

rustbook не собирается, надо починить

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rust_book_ru/60#-:-KXnoDFwo1f_83-BJoW7:b-15jhxj)*

**Comment by mkpankov** [comment]
Вот тут конкретное место https://travis-ci.org/ruRust/rust_book_ru/builds/179984553#L233

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rust_book_ru/60#-:-KXnoQd03xTw9D58ubqa:b-e3f21r)*

**Comment by mkpankov** [comment]
Надо поменять хэш коммита, который чекаутится в rustbook

**Comment by Gordon-F** [comment]
@mkpankov Отправил PR

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rust_book_ru/60)*

**Pull request merged**
